version: '3'
services:

  nginx:
    image: nginx:1.13.3
    container_name: nginx
    depends_on:
      - "node_app"
    ports:
      - "80:80"
    volumes:
      - /vagrant/dockers/nginx/conf.d:/etc/nginx/conf.d
      - /vagrant/dockers/nginx/www:/var/nginx/www
      - /var/log/dockers/nginx/log:/var/log/nginx
    networks:
      - app_network

  node_app:
    image: node:7.10.1
    container_name: node_app
    ports:
      - "8080:8080"
      - "9229:9229"

    volumes:
      - /vagrant/dockers/node/src:/var/node/src
      - /var/log/dockers/node/log:/var/log/node
    working_dir: /var/node/src
    networks:
      - app_network
    command: "bash -c 'npm install && npm config set log_dir /var/log/node && npm start'"

  mongodb:
    image: mongo:3.4.7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - datastrage:/data/db
      - /var/log/dockers/mongodb/log:/var/log/mongodb
    networks:
      - app_network
    command: "bash -c 'mongod --logpath=/var/log/mongodb/mongodb.log --logappend'"

volumes:
  datastrage:

networks:
  app_network: