# -*- mode: ruby -*-
# vi: set ft=ruby :

# List plugins dependencies
# plugins_dependencies = %w( vagrant-vbguest vagrant-docker-compose local-persist)
# plugin_status = false
# plugins_dependencies.each do |plugin_name|
#   unless Vagrant.has_plugin? plugin_name
#     system("vagrant plugin install #{plugin_name}")
#     plugin_status = true
#     puts " #{plugin_name}  Dependencies installed"
#   end
# end
 
# Restart Vagrant if any new plugin installed
# if plugin_status === true
#   exec "vagrant #{ARGV.join' '}"
# else
#   puts "All Plugin Dependencies already installed"
# end

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.33.20"
  

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "dockers/nginx/conf.d", "/var/dockers/nginx/conf.d"
  config.vm.synced_folder "dockers/nginx/www", "/var/dockers/nginx/www"

  config.vm.synced_folder "dockers/node/src", "/var/dockers/node/src", type: "rsync", rsync__exclude: "node_modules"
  config.vm.synced_folder "dockers/node/log", "/var/dockers/node/log"

  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: ["/vagrant/docker-compose.yml"], rebuild: true, project_name: "myproject", run: "always"

end


