# -*- mode: ruby -*-
# vi: set ft=ruby :

# vagrant plugins
if ARGV[0] == 'up'
  plugins_dependencies = %w( vagrant-vbguest vagrant-docker-compose )
  plugin_status = false
  plugins_dependencies.each do |plugin_name|
    unless Vagrant.has_plugin? plugin_name
      puts "#{plugin_name} is required."
      system("vagrant plugin install #{plugin_name}")
      plugin_status = true
    end
  end
  #Restart Vagrant if any new plugin installed
  if plugin_status === true
    exec "vagrant #{ARGV.join' '}"
  else
    puts "All Plugin Dependencies already installed"
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.name = "manjiii_vm"
  end

  config.vm.network "private_network", ip: "192.168.33.20"
  
  config.vm.synced_folder ".", "/vagrant", type: "rsync", 
  rsync__exclude: [ '.git*', 'node_modules*', '.log'  ]

  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: ["/vagrant/docker-compose.yml"], rebuild: true, project_name: "manjiii_nnm_project", run: "always"

end


